version: 2

models:
  - name: stg_raw__ad_spend
    description: This model ingests raw ad spend data from various ad networks and applies basic cleaning
    columns:
      - name: report_date
        description: Date of the report
        data_tests:
          - not_null
      - name: country_code
        description: Country code where ad was served
        data_tests:
          - not_null
      - name: os_name
        description: Operating system (android/ios)
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['android', 'ios']
      - name: acquisition_channel
        description: User acquisition channel/network
        data_tests:
          - not_null
      - name: campaign_name
        description: Campaign name
        data_tests:
          - not_null
      - name: campaign_creative
        description: Creative/ad name
        data_tests:
          - not_null
      - name: ad_spend_usd
        description: Amount spent on ads in USD
        data_tests:
          - not_null
      - name: network_clicks
        description: Clicks reported by network
        data_tests:
          - not_null
      - name: network_impressions
        description: Impressions reported by network
        data_tests:
          - not_null
      - name: network_installs
        description: Installs reported by network
        data_tests:
          - not_null
      - name: adjust_installs
        description: Installs attributed by Adjust
        data_tests:
          - not_null

  - name: stg_raw__installs
    description: "This model ingests raw install data from Adjust and applies basic cleaning"
    columns:
      - name: user_id
        description: "Internal JustPlay user identifier"
        tests:
          - not_null
      - name: adjust_id
        description: "Unique Adjust attribution identifier"
        tests:
          - not_null
      - name: installed_at
        description: "When the app was installed"
        tests:
          - not_null
      - name: country_code
        description: "User's attributed country code"
      - name: os_name
        description: "Operating system (android/ios)"
      - name: acquisition_channel
        description: "Ad network/channel that drove the install"
      - name: campaign_name
        description: "Marketing campaign name"
      - name: campaign_creative
        description: "Specific ad creative shown"
      - name: ad_group_name
        description: "Ad group within campaign"
      - name: tracker_name
        description: "Adjust tracker link token"
      - name: device
        description: "Device model"
      - name: os_version
        description: "Operating system version"
      - name: has_limit_ad_tracking
        description: "Boolean Whether user limited ad tracking"
      - name: idfa
        description: "iOS advertising identifier"
      - name: idfv
        description: "iOS vendor identifier"
      - name: google_ad_id
        description: "Android advertising identifier"

  - name: stg_raw__revenue
    description: "This model ingests raw revenue data from AppLovin and applies basic cleaning"
    columns:
      - name: event_id
        description: "Unique revenue event identifier"
        tests:
          - not_null
      - name: user_id
        description: "Internal JustPlay user identifier"
        tests:
          - not_null
      - name: created_at
        description: "When revenue was generated"
        tests:
          - not_null
      - name: country_code
        description: "Country where revenue was generated"
      - name: platform
        description: "Platform generating revenue"
      - name: revenue_usd
        description: "Revenue amount in USD"
        tests:
          - not_null
      - name: revenue_source
        description: "Third-party monetization tool"
      - name: ad_network
        description: "Network providing the ad (AppLovin only)"
      - name: ad_unit_format
        description: "Ad format (banner, rewarded video, interstitial)"
      - name: ad_unit_name
        description: "AppLovin MAX ad unit name"
      - name: package_name
        description: "Game package where revenue occurred"
      - name: device_id
        description: "Device identifier (AppSetId/IDFV)"
      - name: advertising_id
        description: "Advertising identifier (GAID/IDFA)"